"""empty message

Revision ID: 726050188dbf
Revises: e69e8a5a62bb
Create Date: 2022-01-25 11:18:51.299029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726050188dbf'
down_revision = 'e69e8a5a62bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_name', sa.String(length=100), nullable=False),
    sa.Column('photo_datatime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
