"""empty message

Revision ID: e80a4d189f00
Revises: 3f6a8cb76359
Create Date: 2022-01-26 13:45:21.767407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80a4d189f00'
down_revision = '3f6a8cb76359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'about_me', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'about_me', type_='unique')
    # ### end Alembic commands ###
