"""empty message

Revision ID: 77efa5598d6e
Revises: bed77ed490da
Create Date: 2022-02-10 10:38:50.873043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77efa5598d6e'
down_revision = 'bed77ed490da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('news_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_type_id'], ['news_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
