"""empty message

Revision ID: 89c4e62f9913
Revises: 17c22bb2ed93
Create Date: 2022-02-11 13:18:01.399210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c4e62f9913'
down_revision = '17c22bb2ed93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('desc', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'desc')
    # ### end Alembic commands ###
